server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:homy}?serverTimezone=UTC
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:password123}
    expiration-seconds: 86400

  pageable:
    default-page-size: 20
    index-default: 0

  email:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:emailsendergordito@gmail.com}
    password: ${EMAIL_PASSWORD:ypcb qbzo bkhi uxyt}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: API Generada
        url: /v3/api-docs
      - name: API Especificaci√≥n
        url: /openapi.yaml