server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homy?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: homy_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update   # otras opciones: none, validate, create, create-drop
    show-sql: true       # muestra las consultas en consola
    properties:
      hibernate:
        format_sql: true # formatea el SQL en consola
    database-platform: org.hibernate.dialect.MySQLDialect
app:
  jwt:
    secret: password123
    expiration-seconds: 86400

  pageable:
    default-page-size: 20
    index-default: 0

  email:
    host: smtp.gmail.com
    port: 587
    username: emailsendergordito@gmail.com # Gordito123@
    password: ypcb qbzo bkhi uxyt

springdoc:
  swagger-ui:
    # Swagger UI generado automáticamente con tus controllers
    path: /swagger-ui.html
    
    # Opción: cargar también tu archivo openapi.yaml
    urls:
      - name: API Generada
        url: /v3/api-docs
      - name: API Especificación
        url: /openapi.yaml
