server:
port: 8080
# spring:
# datasource:
# url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
# driverClassName: org.h2.Driver
# username: sa
# password:
# jpa:
# hibernate:
# ddl-auto: update
# show-sql: true
app:
  jwt:
    secret: password123
    expiration-seconds: 86400

springdoc:
  swagger-ui:
    # Swagger UI generado automáticamente con tus controllers
    path: /swagger-ui.html
    
    # Opción: cargar también tu archivo openapi.yaml
    urls:
      - name: API Generada
        url: /v3/api-docs
      - name: API Especificación
        url: /openapi.yaml
